name: Documentation Problem
description: Report an issue with or suggest documentation.
labels: ["docs"]
body:
  - type: markdown
    attributes:
      value: >
        **Thanks for taking the time to report a documentation issue!**


        Documentation problems include everything from typos to missing or
        incorrect technical details in any of the following:
          - [Rocket's Website](https://rocket.rs/)
          - [The Rocket Programming Guide](https://rocket.rs/guide/)
          - [API Docs](https://api.rocket.rs)
          - [Content on GitHub](https://github.com/rwf2/Rocket)

        If we've written it, we want to know how it can be improved.
  - type: dropdown
    validations:
      required: true
    attributes:
      label: What kind of documentation problem are you reporting?
      multiple: true
      options:
        - Typo (PRs welcome!)
        - Unclear Docs
        - Undocumented Feature
        - Broken Links
        - Rendering Issue
        - Grammar Issue
        - Technical Problem
        - Other
  - type: input
    validations:
      required: true
    attributes:
      label: Where is the issue found?
      description: Please provide a direct link to the documentation.
      placeholder: "ex: https://rocket.rs/v0.5/guide/requests/#multiple-segments"
  - type: textarea
    validations:
      required: true
    attributes:
      label: What's wrong?
      description: >
        Please describe what's wrong with the documentation.
  - type: checkboxes
    attributes:
      label: System Checks
      description: "Please confirm all of the following:"
      options:
        - label: I confirmed that the issue still exists on `master` on GitHub.
          required: true
        - label: I was unable to find a previous report of this problem.
          required: true
