name: Suggestion
description: Suggest a change or improvement to existing functionality.
labels: ["suggestion"]
body:
  - type: markdown
    attributes:
      value: >
        **Thanks for taking the time to make a suggestion!**
  - type: input
    validations:
      required: true
    attributes:
      label: API Docs to Existing Functionality
      description: Please provide a direct link to the API docs for the
        functionality you'd like to change.
      placeholder: "ex: https://api.rocket.rs/v0.5/rocket/trait.Sentinel.html"
  - type: textarea
    validations:
      required: true
    attributes:
      label: Problems with Existing Functionality
      description: Please let us know what you think is wrong with the existing functionality.
      placeholder: >
        example: Sentinels don't allow me to access `Foo`, but I'd like to because...

        example: Feature Z exists, but it has these drawbacks. What if...
  - type: textarea
    validations:
      required: true
    attributes:
      label: Suggested Changes
      description: >
        How do you propose the existing functionality be changed? Code examples
        are particular useful.
  - type: textarea
    validations:
      required: true
    attributes:
      label: Alternatives Considered
      description: >
        Instead of making a change to Rocket, please describe alternative
        solutions using existing features or new features you've considered.
  - type: textarea
    attributes:
      label: Additional Context
      description: Feel free to provide any additional context for your suggestion.
  - type: checkboxes
    attributes:
      label: System Checks
      description: "Please confirm all of the following:"
      options:
        - label: >
            I do not believe that this suggestion can or should be implemented
            outside of Rocket.
          required: true
        - label: I was unable to find a previous suggestion for this change.
          required: true
